<?php
declare(strict_types=1);

namespace app\common\validate;

use think\Validate;

class Store extends Validate
{
    protected $rule = [
        'store_id|店铺信息'            => 'require',
        'member_id|会员信息'           => ['require', 'unique:store'],
        'store_name|店铺名称'          => 'require',
        'category|主营分类'            => 'require',
        'goods_classify_id|主营分类'   => 'require',
        'brand_classify_id|主营品牌'   => 'require',
        'shop|店铺类型'                => 'require',
        'type|公司店铺分类'              => 'require',
        'status|审核状态'              => 'require',
        'province|省份'              => 'require',
        'city|城市'                  => 'require',
        'area|地区'                  => 'require',
        'address|详细地址'             => 'require',
        'lng|经度'                   => 'require',
        'lat|纬度'                   => 'require',
        'price|价格'                 => 'require',
        'number|数量'                => 'require',
        'goods_style|店铺模式'         => ['require', 'in:0,1'],
        'is_pay_delivery|是否开启货到付款' => ['require', 'in:0,1'],
        'is_express|是否开启全国包邮'      => ['require', 'in:0,1'],
        'keywords|店铺关键字'           => ['require', 'max:100'],
        'describe|店铺简介'            => ['require', 'max:100'],
        'phone|客服电话'               => ['require', 'reg' => '^(([04]\d{2,3}-\d{7,8})|(1[35846]\d{9}))$'],
        'image|店铺LOGO'             => 'image',
        'back_images|店铺背景图'        => 'image',
        'brand_images|店铺品牌甄选展示图'   => 'image',
        'good_images|店铺发现好店展示图'    => 'image',
        'reason|注销原因'              => 'require',
        'logout_reason|注销原因'       => 'require',
        'end_time|店铺到期时间'          => 'dateFormat:Y-m-d',
        'logo|店铺LOGO'              => 'require',
        'is_city|同城配送'             => 'require|in:0,1',
        'is_pay_delivery|货到付款'     => 'require|in:0,1',
        'is_shop|门店自提'             => 'require|in:0,1',
        'is_express|全国包邮'          => 'require|in:0,1',
        'is_good|发现好店'             => 'require|in:0,1',
        'brand_image|店铺品牌甄选展示图'   => 'require',
        'good_image|发现好店展示图'       => 'require',
        'back_image|店铺背景图'         => 'require',
    ];

    protected $message = [
        'store_id.require'          => '不可为空',
        'store_name.require'        => '不可为空',
        'category.require'          => '不可为空',
        'goods_classify_id.require' => '不可为空',
        'brand_classify_id.require' => '不可为空',
        'member_id.require'         => '不可为空',
        'member_id.unique'          => '该账号已经成为店主,请勿重复操作',
        'shop.require'              => '不可为空',
        'type.require'              => '不可为空',
        'status.require'            => '不可为空',
        'province.require'          => '不可为空',
        'city.require'              => '不可为空',
        'area.require'              => '不可为空',
        'address.require'           => '不可为空',
        'lng.require'               => '不可为空',
        'lat.require'               => '不可为空',
        'price.require'             => '不可为空',
        'number.require'            => '不可为空',
        'goods_style.require'       => '不可为空',
        'goods_style.in'            => '数据错误',
        'is_pay_delivery.require'   => '必须选择',
        'is_pay_delivery.in'        => '格式错误',
        'is_express.require'        => '必须选择',
        'is_express.in'             => '格式错误',
        'keywords.require'          => '不可为空',
        'keywords.max'              => '不能超过100个字符',
        'describe.require'          => '不可为空',
        'describe.max'              => '不能超过100个字符',
        'phone.require'             => '不可为空',
        'phone.reg'              => '格式错误',
        'reason.require'            => '不可为空',
        'logout_reason.require'     => '不可为空',
        'end_time.dateFormat'       => '格式错误',
        'logo.require'              => '必须上传',
        'is_city.require'           => '必须选择',
        'is_city.in'                => '格式错误',
        'is_shop.require'           => '必须选择',
        'is_shop.in'                => '格式错误',
        'is_good.require'           => '必须选择',
        'is_good.in'                => '格式错误',
        'good_image.require'        => '必须上传',
        'back_image.require'        => '必须上传',
        'brand_image.require'        => '必须上传',
    ];

    protected $scene = [
        'create'                      => [
            'store_name',
            'member_id',
            'category',
            'shop',
            'type',
            'status',
            'province',
            'city',
            'area',
            'address',
            'lng',
            'lat',
        ],
        'edit'                        => [
            'store_id',
            'store_name',
            'category',
            'shop',
            'type',
            'status',
            'province',
            'city',
            'area',
            'address',
            'lng',
            'lat',
        ],
        'index'                       => ['store_id'],
        'head'                        => ['store_id'],
        'info'                        => ['store_id'],
        'collect_store'               => ['store_id'],
        'collect_store_delete'        => ['collect_goods_id'],
        'view_collect_store_delete'   => ['goods_id'],
        'good_list'                   => ['category'],
        'store_ranking'               => ['goods_classify_id'],
        'brand_list'                  => ['brand_classify_id'],
        'create_store'                => ['store_name', 'category', 'shop', 'province', 'city', 'area', 'address'],
        'common_confirm_order'        => ['store_id', 'price', 'number'],
        'client'                      => ['store_id', 'shop'],
        'master'                      => ['store_name', 'member_id', 'category', 'shop', 'type', 'status'],

        // 更新店铺信息
        'client_update_store_info'    => [
            // 店铺类型
            'shop',
            // 是否开启付款付款
            'is_pay_delivery',
            // 是否开启全国包邮
            'is_express',
            // 店铺关键字
            'keywords',
            // 店铺简介
            'describe',
        ],
        'client_update_images'        => [
            'image',
            'back_images',
            'good_images',
            'brand_images',
        ],
        'client_update_contact'       => [
            // 省
            'province',
            // 市
            'city',
            // 区
            'area',
            // 地址
            'address',
            // 经度
            'lng',
            // 纬度
            'lat',
            // 客服电话
            "phone",
        ],
        'client_update_fitment'       => [
            // 店铺模式
            'goods_style' => [
                'require',
                'in:0,1',
            ],
        ],
        'master_create_store'         => [
            'category',
            'store_name',
            'logo',
            'phone',
            'province',
            'city',
            'area',
            'address',
            'lng',
            'lat',
            'sort',
            'keywords',
            'describe',
            'end_time',
            'type',
        ],
        'master_recreate_store'         => [
            'member_id',
            'category',
            'store_name',
            'logo',
            'phone',
            'province',
            'city',
            'area',
            'address',
            'lng',
            'lat',
            'sort',
            'keywords',
            'describe',
            'end_time',
            'type',
        ],
        'master_edit_store'           => [
            'category',
            'store_name',
            'logo',
            'phone',
            'province',
            'city',
            'area',
            'address',
            'lng',
            'lat',
            'sort',
            'keywords',
            'describe',
            'end_time',
        ],
        // 平台后台创建店铺 设置资料
        'master_create_store_setting' => [
            'is_city',
//            'is_pay_delivery',
            'is_shop',
//            'is_express',
            'is_good',
            'good_image',
            'brand_image',
        ],
        // 平台后台穿件店铺 店铺装修资料
        'master_create_store_fitment' => [
            'back_image',
            'goods_style',
        ],
        'master_update_images'        => ['store_id'],
        'master_update_fitment'       => ['goods_style'],
        'master_update_contact'       => ['province', 'city', 'area', 'address', 'lng', 'lat', 'store_id'],
        'log_out'                     => ['reason', 'store_id'],
    ];
}